spring.application.name=Asclepio

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

api.security.token.secret=${JWT_SECRET:my-secreat-key}

spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true



storage-service.url=http://localhost:8081
services.storage.url=http://localhost:8081

#
#storage-service.url=${STORAGE_SERVICE_URL}
#services.storage.url=${STORAGE_SERVICE_URL}


