# Nome da Aplicação
spring.application.name=Asclepio

# Configurações de Banco de Dados
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true

# Segurança / JWT
api.security.token.secret=${JWT_SECRET:my-secreat-key}
security.password.pepper=${PASSWORD_PEPPER}

# Configurações de Upload de Arquivos (Multipart)
spring.servlet.multipart.max-file-size=15MB
spring.servlet.multipart.max-request-size=15MB

# Configurações do Cloudflare R2 / S3 Storage
r2.access-key=${R2_ACCESS_KEY}
r2.secret-key=${R2_SECRET_KEY}
r2.bucket=${R2_BUCKET}
r2.endpoint=${R2_ENDPOINT}
r2.public-url=${R2_PUBLIC_URL}